# CRISP Pipeline Conda Environment
# Create environment: conda env create -f environment.yml
# Activate environment: conda activate crisp-pipeline

name: crisp-pipeline
channels:
  - conda-forge
  - defaults

dependencies:
  # Python version
  - python=3.8
  
  # Core data processing
  - pandas>=1.3.0
  - numpy>=1.21.0
  
  # Progress bars
  - tqdm>=4.62.0
  
  # Visualization
  - matplotlib>=3.4.0
  - seaborn>=0.11.0
  
  # Jupyter notebooks support
  - jupyter
  - ipykernel
  
  # Additional scientific computing
  - scipy>=1.7.0
  - scikit-learn>=1.0.0
  
  # Development tools (optional)
  - ipython
  - black  # Code formatter
  - pylint  # Code linter
  
  # Additional packages via pip (if needed)
  - pip
  - pip:
      # Add any pip-only packages here if needed
      # For example:
      # - some-package==1.0.0